// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"go.uber.org/zap"
	"gopkg.in/natefinch/lumberjack.v2"
	"stream/app/middleware"
	"stream/config"
	"stream/router"
)

// Injectors from wire.go:

func wireApp(configuration *config.Configuration, lumberjackLogger *lumberjack.Logger, zapLogger *zap.Logger) (*App, func(), error) {
	ginLogger := middleware.NewLogger()
	engine := router.NewRouter(configuration, zapLogger, ginLogger)
	server := newHttpServer(configuration, engine)
	app := newApp(configuration, zapLogger, server)
	return app, func() {
	}, nil
}
